import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :apiary, ApiaryWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Redirect plain HTTP to HTTPS and send HSTS. `:force_ssl` is read at compile time, so
# the runtime decision (is PUBLIC_URL https or http?) is made through the `:conn`
# exclusion: an instance published over plain http is never redirected. Behind a
# TLS-terminating reverse proxy the proxy must send `X-Forwarded-Proto: https`.
# `/health` is excluded so a load balancer can probe it over http.
config :apiary, ApiaryWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      hosts: ["localhost", "127.0.0.1"],
      paths: ["/health"],
      conn: {Apiary.Release, :plain_http?, []}
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Requests are logged once, as JSON, by the telemetry handler attached in
# Apiary.Application (see config/runtime.exs); the human-readable Phoenix request
# logger stays off here so nothing is logged twice.
config :phoenix, :logger, false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
