defmodule ApiaryWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :apiary

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_apiary_key",
    signing_salt: "pFOPn1LM",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :apiary,
    gzip: not code_reloading?,
    only: ApiaryWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # The documentation, from the tree built for the instance's features (decision 0070):
  # `priv/static/docs` holds one per set of features, and `dir/0` names the one to read.
  plug Plug.Static,
    at: "/docs",
    from: {ApiaryWeb.DocsController, :dir, []},
    gzip: not code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :apiary
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # Emits [:phoenix, :endpoint, :start | :stop]. In production the JSON request log
  # (LoggerJSON.Plug, attached in Apiary.Application) listens to the stop event; the
  # Phoenix request logger is off there, so each request produces one line.
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # A delivery to the events endpoint is signed over its raw bytes and verified
  # before it is parsed: its body is read and kept here, and the parsers skip it.
  plug ApiaryWeb.Contract.RawBody
  plug :parse_body

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # A route of a feature this instance does not have is a path the router does not know.
  plug ApiaryWeb.Features.Routes, ApiaryWeb.Router
  plug ApiaryWeb.Router

  @parsers Plug.Parsers.init(
             parsers: [:urlencoded, :multipart, :json],
             pass: ["*/*"],
             json_decoder: Phoenix.json_library()
           )

  defp parse_body(%Plug.Conn{assigns: %{raw_body: _}} = conn, _opts), do: conn
  defp parse_body(conn, _opts), do: Plug.Parsers.call(conn, @parsers)
end
